version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - cert
skip_tags: true
environment:
  matrix:
  - solution_name: Client.SDK/Client.SDK.sln
  - solution_name: Server.SDK/Server.SDK.sln
build_script:
  - cmd: nuget restore %solution_name%
  - cmd: msbuild %solution_name%